// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyigukjmmqrpapehfwoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aWd1a2ptbXFycGFwZWhmd295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzI2OTMsImV4cCI6MjA2NDIwODY5M30.yIPQY2ELY4OLimVpQpoEMPGvWHhsJnjbGZHxkHabBco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);